name: call-cicd-class-library

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  call-class-library:
    uses: projeto-devops-gabriela/esteiras-devops/.github/workflows/esteira-teste-conexao.yaml@main
    with:
      project-directory: 'src/ClassLibrary1'
      project-type: 'ClassLibrary'
      build-configuration: Debug
    secrets: inherit